# Generated by Django 5.2.1 on 2025-06-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_transactions_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
